---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - "skip-changelog"
    reviewers:
      - redhat-developer/extester-maintainers
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    reviewers:
      - redhat-developer/extester-maintainers
