name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]
      fail-fast: false
    env:
      TEST_RESOURCES: test-resources
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: npm-ci
        run: npm ci

      - name: npm-compile
        run: npm run compile

      - name: UI test (macOS, windows)
        if: matrix.os != 'ubuntu-24.04'
        run: npm run ui-test

      - name: UI test (linux)
        if: matrix.os == 'ubuntu-24.04'
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm run ui-test

      - name: Store UI test logs
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: logs-${{ matrix.os }}
          path: test-resources/settings/logs/*

      - name: Store UI Test screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots-${{ matrix.os }}
          path: test-resources/screenshots/*.png

  check:
    if: always()
    runs-on: ubuntu-24.04
    name: 🚦 Status Check
    needs: [main]
    steps:
      - name: ℹ️ Test Matrix Result
        run: |
          echo result = ${{ needs.main.result }}
      - name: ✅ Status Check - success
        if: ${{ needs.main.result == 'success' }}
        run: |
          echo "All tests successfully completed!"
          exit 0
      - name: ❌ Status Check - failure
        if: ${{ needs.main.result != 'success' }}
        run: |
          echo "Status Check failed!"
          exit 1
